[build]
  publish = "out/"
  command = "npm run deploy"

[context.deploy-preview.environment]
  ENDPOINT="https://safira20.herokuapp.com"
  API_AUTH_SIGN_IN="/api/auth/sign_in"
  API_AUTH_SIGN_UP="/api/auth/sign_up"
  API_AUTH_RESET_PASSWORD="/api/auth/passwords"
  API_USER_INFO="/api/v1/user"
  API_REFERRALS="/api/v1/referrals"
  API_BADGES="/api/v1/badges"
  API_ATTENDEE="/api/v1/attendee"
  API_ATTENDEES="/api/v1/attendees"
  API_LEADERBOARD="/api/v1/leaderboard"
  API_COMPANIES="/api/v1/companies"
  API_REDEEMS="/api/v1/redeems"

[context.dev.environment]
  ENDPOINT="https://safira20.herokuapp.com"
  API_AUTH_SIGN_IN="/api/auth/sign_in"
  API_AUTH_SIGN_UP="/api/auth/sign_up"
  API_AUTH_RESET_PASSWORD="/api/auth/passwords"
  API_USER_INFO="/api/v1/user"
  API_REFERRALS="/api/v1/referrals"
  API_BADGES="/api/v1/badges"
  API_ATTENDEE="/api/v1/attendee"
  API_ATTENDEES="/api/v1/attendees"
  API_LEADERBOARD="/api/v1/leaderboard"
  API_COMPANIES="/api/v1/companies"
  API_REDEEMS="/api/v1/redeems"

[context.master.environment]
  ENDPOINT="https://safira.enei.pt"
  API_AUTH_SIGN_IN="/api/auth/sign_in"
  API_AUTH_SIGN_UP="/api/auth/sign_up"
  API_AUTH_RESET_PASSWORD="/api/auth/passwords"
  API_USER_INFO="/api/v1/user"
  API_REFERRALS="/api/v1/referrals"
  API_BADGES="/api/v1/badges"
  API_ATTENDEE="/api/v1/attendee"
  API_ATTENDEES="/api/v1/attendees"
  API_LEADERBOARD="/api/v1/leaderboard"
  API_COMPANIES="/api/v1/companies"
  API_REDEEMS="/api/v1/redeems"
